# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_ui/controller/controller.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ControlWindow(object):
    def setupUi(self, ControlWindow):
        ControlWindow.setObjectName("ControlWindow")
        ControlWindow.resize(399, 295)
        self.frame_2 = QtWidgets.QFrame(ControlWindow)
        self.frame_2.setGeometry(QtCore.QRect(40, 30, 301, 251))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.forwardButton = QtWidgets.QPushButton(self.frame_2)
        self.forwardButton.setObjectName("forwardButton")
        self.gridLayout.addWidget(self.forwardButton, 0, 0, 1, 1)
        self.turnRButton = QtWidgets.QPushButton(self.frame_2)
        self.turnRButton.setObjectName("turnRButton")
        self.gridLayout.addWidget(self.turnRButton, 2, 2, 1, 1)
        self.downButton = QtWidgets.QPushButton(self.frame_2)
        self.downButton.setObjectName("downButton")
        self.gridLayout.addWidget(self.downButton, 1, 2, 1, 1)
        self.turnLButton = QtWidgets.QPushButton(self.frame_2)
        self.turnLButton.setObjectName("turnLButton")
        self.gridLayout.addWidget(self.turnLButton, 2, 0, 1, 1)
        self.backwardButton = QtWidgets.QPushButton(self.frame_2)
        self.backwardButton.setObjectName("backwardButton")
        self.gridLayout.addWidget(self.backwardButton, 0, 2, 1, 1)
        self.upButton = QtWidgets.QPushButton(self.frame_2)
        self.upButton.setObjectName("upButton")
        self.gridLayout.addWidget(self.upButton, 1, 0, 1, 1)
        self.KeyboardCtrl = QtWidgets.QPushButton(self.frame_2)
        self.KeyboardCtrl.setObjectName("KeyboardCtrl")
        self.gridLayout.addWidget(self.KeyboardCtrl, 0, 1, 1, 1)

        self.retranslateUi(ControlWindow)
        QtCore.QMetaObject.connectSlotsByName(ControlWindow)

    def retranslateUi(self, ControlWindow):
        _translate = QtCore.QCoreApplication.translate
        ControlWindow.setWindowTitle(_translate("ControlWindow", "Form"))
        self.forwardButton.setText(_translate("ControlWindow", "前进"))
        self.turnRButton.setText(_translate("ControlWindow", "右转"))
        self.downButton.setText(_translate("ControlWindow", "下降"))
        self.turnLButton.setText(_translate("ControlWindow", "左转"))
        self.backwardButton.setText(_translate("ControlWindow", "后退"))
        self.upButton.setText(_translate("ControlWindow", "上升"))
        self.KeyboardCtrl.setText(_translate("ControlWindow", "键盘控制"))
