# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\SPBA\Realtime\realtime_sensorData.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget

class Ui_sensorData(object):
    def setupUi(self, sensorData):
        sensorData.setObjectName("sensorData")
        sensorData.resize(1204, 846)
        self.gridLayoutWidget = QtWidgets.QWidget(sensorData)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 1141, 811))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.magnetometer = PlotWidget(self.gridLayoutWidget)
        self.magnetometer.setObjectName("magnetometer")
        self.gridLayout.addWidget(self.magnetometer, 3, 0, 1, 1)
        self.imu_angular = PlotWidget(self.gridLayoutWidget)
        self.imu_angular.setObjectName("imu_angular")
        self.gridLayout.addWidget(self.imu_angular, 0, 2, 1, 1)
        self.gps_geo = PlotWidget(self.gridLayoutWidget)
        self.gps_geo.setObjectName("gps_geo")
        self.gridLayout.addWidget(self.gps_geo, 3, 1, 1, 1)
        self.Main_View = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.Main_View.setObjectName("Main_View")
        self.gridLayout.addWidget(self.Main_View, 0, 0, 3, 2)
        self.imu_linear = PlotWidget(self.gridLayoutWidget)
        self.imu_linear.setObjectName("imu_linear")
        self.gridLayout.addWidget(self.imu_linear, 2, 2, 1, 1)
        self.barometer = PlotWidget(self.gridLayoutWidget)
        self.barometer.setObjectName("barometer")
        self.gridLayout.addWidget(self.barometer, 3, 2, 1, 1)

        self.retranslateUi(sensorData)
        QtCore.QMetaObject.connectSlotsByName(sensorData)

    def retranslateUi(self, sensorData):
        _translate = QtCore.QCoreApplication.translate
        sensorData.setWindowTitle(_translate("sensorData", "Form"))

