# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Uav_hardware_in_the_loop_simulation_platform\qtProect\realtime.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Realtime(object):
    def setupUi(self, Realtime):
        Realtime.setObjectName("Realtime")
        Realtime.resize(1211, 852)
        self.gridLayoutWidget = QtWidgets.QWidget(Realtime)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 1171, 811))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.front_right = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.front_right.setObjectName("front_right")
        self.gridLayout.addWidget(self.front_right, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.bottom_center = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.bottom_center.setObjectName("bottom_center")
        self.gridLayout.addWidget(self.bottom_center, 3, 1, 1, 1)
        self.front_left = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.front_left.setObjectName("front_left")
        self.gridLayout.addWidget(self.front_left, 1, 0, 1, 1)
        self.back_center = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.back_center.setObjectName("back_center")
        self.gridLayout.addWidget(self.back_center, 5, 1, 1, 1)
        self.front_center = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.front_center.setObjectName("front_center")
        self.gridLayout.addWidget(self.front_center, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 1, 1, 1)

        self.retranslateUi(Realtime)
        QtCore.QMetaObject.connectSlotsByName(Realtime)

    def retranslateUi(self, Realtime):
        _translate = QtCore.QCoreApplication.translate
        Realtime.setWindowTitle(_translate("Realtime", "Form"))
        self.label_2.setText(_translate("Realtime", " Front center camera"))
        self.label_3.setText(_translate("Realtime", " Front right camera"))
        self.label.setText(_translate("Realtime", " Front left camera"))
        self.label_4.setText(_translate("Realtime", " Bottom center camera"))
        self.label_5.setText(_translate("Realtime", " Back center camera"))
