# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Uav_hardware_in_the_loop_simulation_platform\qtProect\Data_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget

class Ui_Display_Win(object):
    def setupUi(self, Display_Win):
        Display_Win.setObjectName("Display_Win")
        Display_Win.resize(1405, 881)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Display_Win)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(70, 20, 451, 781))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(5, 10, 10, 10)
        self.formLayout_2.setVerticalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.Segment_view = QtWidgets.QGraphicsView(self.formLayoutWidget_2)
        self.Segment_view.setObjectName("Segment_view")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Segment_view)
        self.Depth_view = QtWidgets.QGraphicsView(self.formLayoutWidget_2)
        self.Depth_view.setObjectName("Depth_view")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Depth_view)
        self.Scene_view = QtWidgets.QGraphicsView(self.formLayoutWidget_2)
        self.Scene_view.setObjectName("Scene_view")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Scene_view)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.gridLayoutWidget = QtWidgets.QWidget(Display_Win)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(540, 30, 841, 631))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.Altitude = PlotWidget(self.gridLayoutWidget)
        self.Altitude.setObjectName("Altitude")
        self.gridLayout_2.addWidget(self.Altitude, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.acceleration = PlotWidget(self.gridLayoutWidget)
        self.acceleration.setObjectName("acceleration")
        self.gridLayout_2.addWidget(self.acceleration, 2, 2, 1, 1)
        self.Latitude = PlotWidget(self.gridLayoutWidget)
        self.Latitude.setObjectName("Latitude")
        self.gridLayout_2.addWidget(self.Latitude, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 1, 1, 1)
        self.Longitutde = PlotWidget(self.gridLayoutWidget)
        self.Longitutde.setObjectName("Longitutde")
        self.gridLayout_2.addWidget(self.Longitutde, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        self.Pressure = PlotWidget(self.gridLayoutWidget)
        self.Pressure.setObjectName("Pressure")
        self.gridLayout_2.addWidget(self.Pressure, 2, 1, 1, 1)
        self.Position = PlotWidget(self.gridLayoutWidget)
        self.Position.setObjectName("Position")
        self.gridLayout_2.addWidget(self.Position, 0, 0, 1, 1)

        self.retranslateUi(Display_Win)
        QtCore.QMetaObject.connectSlotsByName(Display_Win)

    def retranslateUi(self, Display_Win):
        _translate = QtCore.QCoreApplication.translate
        Display_Win.setWindowTitle(_translate("Display_Win", "Form"))
        self.label_4.setText(_translate("Display_Win", "Segment"))
        self.label_5.setText(_translate("Display_Win", "Depth"))
        self.label_6.setText(_translate("Display_Win", "Scene"))
        self.label_9.setText(_translate("Display_Win", "Acceleration"))
        self.label_2.setText(_translate("Display_Win", "Latitude"))
        self.label.setText(_translate("Display_Win", "Position"))
        self.label_7.setText(_translate("Display_Win", "Altitude"))
        self.label_8.setText(_translate("Display_Win", "Pressure"))
        self.label_3.setText(_translate("Display_Win", "Longitude"))

